server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/** #路由到商品的微服务
    search-service: /search/** #搜索微服务
    user-service: /user/** #用户微服务
    auth-service: /auth/** #授权微服务
    cart-service: /cart/** #购物车微服务
    order-service: /order/** #订单微服务
  add-host-header: true #携带请求本身的head头信息，  解决cookie写入问题
  sensitive-headers: #配置禁止使用的头信息，这里设置为null，否则set-cookie无效
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  eureka:
    enabled: true
leyou:
  jwt:
    pubKeyPath: F:\\IdeaProjects\\leyou1\\tools\\rsa\\rsa.pub # 公钥地址
    cookieName: LeYou_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item