server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.201.130
    username: leyou
    password: leyou
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: LTAI4GDXKZDcCjqXgdfXnZS6 # 你自己的accessKeyId
    accessKeySecret: WfuElw6inasg5VRnk0DGZhotgSxgLN # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 # 模板名称