server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.201.130
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
leyou:
  jwt:
    pubKeyPath: F:\\IdeaProjects\\leyou1\\tools\\rsa\\rsa.pub # 公钥地址
    cookieName: LeYou_TOKEN
